name: Palettes
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  flutter_file_downloader: ^2.0.0
  animate_do: ^3.3.4
  ionicons: ^0.2.2
  flutter_riverpod: ^2.5.1
  gap: ^3.0.1
  fancy_shimmer_image: ^2.0.3
  flutter_wallpaper_manager: ^0.0.4
  rive: ^0.13.12
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  hydrated_bloc: ^9.1.5
  iconsax: ^0.0.8
  intl: ^0.19.0
  google_nav_bar: ^5.0.6
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/Backgrounds/
    - assets/icons/
    - assets/RiveAssets/
    - assets/avaters/
    - assets/mock/
    - assets/
    # Ensure this is included if you have other assets
  fonts:
    - family: GummyBear
      fonts:
        - asset: assets/fonts/GummyBear.ttf
